CREATE TABLE "CARS" (
    "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "COLOR" VARCHAR(32),
    "MODEL" VARCHAR(32),
    "PAYMENT" DOUBLE,
    "LICENSE_PLATE" VARCHAR(8),
    "STATUS" BOOLEAN
);

CREATE TABLE "CUSTOMERS" (
    "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "FIRST_NAME" VARCHAR(50),
    "LAST_NAME" VARCHAR(50),
    "ADDRESS" VARCHAR(100),
    "PHONE_NUMBER" VARCHAR(32),
    "DRIVERS_LICENSE" VARCHAR(20),
    "STATUS" BOOLEAN
);

CREATE TABLE "RENTS" (
    "ID" INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "CAR" INTEGER NOT NULL REFERENCES CARS(ID),    
    "CUSTOMER" INTEGER NOT NULL REFERENCES CUSTOMERS(ID),
    "RENT_DATE" DATE,
    "DUE_DATE" DATE
);